config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get '/contact' => 'contact#index'
  root 'welcome#index'
  resources :projects
  resources :posts

  get '*path' => redirect('/')
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/project.rb
class Project < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  def index
    @posts = Post.all.order("created_at desc").paginate(page: params[:page], :per_page => 4)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new post_params

    if @post.save
      redirect_to @post, notice: "Post is saved."
    else
      render 'new', notice: "Saving was unsuccessful."
    end
  end

  def show
  end

  def edit
  end

  def update
    if @post.update post_params
      redirect_to @post, notice: "Successfully updated!"
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :content, :slug)
  end

  def find_post
    @post = Post.friendly.find(params[:id])
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :find_project, only: [:show, :edit, :update, :destroy]
  def index
    @projects = Project.all.order("created_at desc").paginate(page: params[:page], :per_page => 4)
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new project_params

    if @project.save
      redirect_to @project, notice: "Project is saved!"
    else
      render 'new', notice: "Project couldnot be saved!"
    end
  end

  def show
  end

  def edit
  end

  def update
    if @project.update project_params
      redirect_to @project, notice: "Project is updated!"
    else
      render 'edit'
    end
  end

  def destroy
    @project.destroy
    redirect_to projects_path
  end

  private

  def project_params
    params.require(:project).permit(:title, :description, :link, :slug)
  end

  def find_project
    @project = Project.friendly.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contact/index.html.erb
<h1>UNDER CONSTRUCTION</h1>

<p id="email">
  nkrisi95@gmail.com
</p>


<div class="sign_out">
  <% if user_signed_in? %>
  <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kristóf Nagy - Full Stack Developer</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href='https://fonts.googleapis.com/css?family=Work+Sans:400,700' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default navbar-centered fixed" role="navigation">
      <ul class="nav navbar-nav">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Posts", posts_path %></li>
        <li><%= link_to "Projects", projects_path %></li>
        <li><%= link_to "Contact", contact_path %></li>
      </ul>
  </nav>

  <% if notice %>
  <p class="notice"><%= notice %></p>
  <% elsif alert %>
  <p class="alert"><%= alert %></p>
  <% end %>

<div class="container">
<%= yield %>
</div>


</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <% if @post.errors.any? %>
  <h2><%= pluralize(@post.errors.count, "error") %> preventer this post from saving:</h2>
  <ul>
    <% @post.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= f.label :title %><br>
<%= f.text_field :title %>

<br>
<br>

<%= f.label :content, "Write your content here" %><br>
<%= f.text_area :content %>

<br>
<br>

<%= f.submit %>

<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

 <%= render "form" %>

app/views/posts/index.html.erb
<h1>My Posts</h1>

<% @posts.each do |post| %>
  <div class="post">
    <h3><%= link_to post.title, post %> <br><span class="date"> <%= post.created_at.strftime('%Y, %B %d')%></span></h3>

    <p><%= truncate(post.content, length: 80,) %></p>
  </div>
<% end %>
<%= will_paginate @posts %>

<div class="sign_out">
  <% if user_signed_in? %>
  <li><%= link_to "New Post", new_post_path%></li>
  <% end %>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>
 <%= render "form" %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>

<p>
  <%= @post.content %>
</p>

<br>
<br>

<% if user_signed_in? %>
  <%= link_to "Edit Post", edit_post_path(@post) %>
  <%= link_to "Delete Post", post_path(@post), method: :delete, data: { confirm: "Are you sure you want to delete this post?"} %>
<% end %>

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>
  <% if @project.errors.any? %>
  <h2><%= pluralize(@project.errors.count, "error") %> preventer this project from saving:</h2>
  <ul>
    <% @project.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= f.label :title %><br>
<%= f.text_field :title %>

<br>
<br>

<%= f.label :description, "Write your content here" %><br>
<%= f.text_area :description %>

<br>
<br>

<%= f.label :link, "Link to the project" %><br>
<%= f.text_field :link %>

<br>
<br>

<%= f.submit %>

<% end %>

app/views/projects/edit.html.erb
<h1>Edit Post</h1>

 <%= render "form" %>

app/views/projects/index.html.erb
<h1>My Projects</h1>

<% @projects.each do |project| %>
  <div class="post">
    <h3><%= link_to project.title, project %> <br><span class="date"> <%= project.created_at.strftime('%Y, %B %d') %></span></h3>
    <p><%= truncate(project.description, length: 80,) %></p>
    <a href="<%= project.link %>" target="_blank">Visit <%= project.title %></a>
  </div>
<% end %>

<%= will_paginate @posts %>

<div class="sign_out">
  <% if user_signed_in? %>
  <li><%= link_to "New Project", new_project_path%></li>
  <% end %>
</div>

app/views/projects/new.html.erb
<h1>New Project</h1>
 <%= render "form" %>

app/views/projects/show.html.erb
<h1><%= @project.title %></h1>

<p>
  <%= @project.description %>
</p>


<a href="http://<%= @project.link %>" target="_blank"><%= @project.link %></a>


<br>
<br>

<% if user_signed_in? %>
  <%= link_to "Edit Project", edit_project_path(@project) %>
  <%= link_to "Delete Project", post_path(@project), method: :delete, data: { confirm: "Are you sure you want to delete this post?"} %>
<% end %>

app/views/welcome/index.html.erb
<div id="welcome">
  <h1>Kristóf Nagy <br> <hr> Full Stack Developer</h1>
  <p>XOXO williamsburg sustainable, fap bitters man braid trust fund cred ramps drinking vinegar helvetica normcore humblebrag craft beer photo booth. Cornhole synth chartreuse pork belly, cliche street art church-key pug chicharrones tilde ennui disrupt skateboard. Taxidermy before they sold out fap YOLO, tacos biodiesel flannel echo park williamsburg semiotics twee stumptown. Ethical polaroid distillery, synth fap brooklyn tofu iPhone heirloom keytar. Art party mlkshk disrupt irony twee chillwave PBR&B lomo authentic iPhone, occupy ennui master cleanse. Knausgaard beard poutine cliche, four dollar toast man braid cred polaroid deep v fashion axe gochujang plaid chillwave. Next level tofu pickled, pop-up small batch put a bird on it salvia letterpress.</p>
</div>

<div class="sign_out">
  <% if user_signed_in? %>
  <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
  <% end %>
</div>